# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxRealm'
  pod 'RealmSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'Wormholy', :configurations => ['Debug']
  pod 'SnapKit'
  target 'CurrencyAppTests' do
    # Pods for testing
  end

  target 'CurrencyAppUITests' do
    # Pods for testing
  end

end
